### ISSUE TITLE
Receiving Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by MajorLOL** [cjekel/tindetheus#54]
Greetings, here is my setup:
![image](https://user-images.githubusercontent.com/56225967/106653009-8cffb480-6596-11eb-922b-1701f82e4f8a.png)
![image](https://user-images.githubusercontent.com/56225967/106653384-07c8cf80-6597-11eb-9e48-b3be005928f2.png)
![image](https://user-images.githubusercontent.com/56225967/106653510-2d55d900-6597-11eb-99ba-e18fb4603711.png)
can anyone tell me what i am doing wrong?

Thank you.

**Comment by MajorLOL** [comment]
Fixed the problem myself,
Seems like models needed to be in same folder and also folder needed to be directed to
docker/tinder/tinder:/tindetheus 

Problem now is receiving:
![image](https://user-images.githubusercontent.com/56225967/106723287-3d0d0600-6607-11eb-8439-6c141c94ce39.png)

forward to solutions :) ill keep you posted who know maybe someone els will need it in the furture

**Comment by cjekel** [comment]
> Fixed the problem myself,
>
> Seems like models needed to be in same folder and also folder needed to be directed to
> docker/tinder/tinder:/tindetheus
> 
> Problem now is receiving:
> ![image](https://user-images.githubusercontent.com/13884657/106771420-c7e40580-65f3-11eb-94b4-83b04f00339c.png)
> 
> forward to solutions :) ill keep you posted who know maybe someone els will need it in the furture

**Comment by MajorLOL** [comment]
did i not delete that? :)
seemed not to be the answer

**Comment by cjekel** [comment]
Hmm seems the ubuntu build has changed a bit. This was my first try in docker:

```
root@ac1f190e018a:/tinder# tindetheus browse
Traceback (most recent call last):
  File "/usr/local/bin/tindetheus", line 33, in <module>
    sys.exit(load_entry_point('tindetheus', 'console_scripts', 'tindetheus')())
  File "/usr/local/bin/tindetheus", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.6/dist-packages/importlib_metadata/__init__.py", line 93, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tindetheus/tindetheus/__init__.py", line 1, in <module>
    from .tindetheus import *  # noqa F401
  File "/tindetheus/tindetheus/tindetheus.py", line 46, in <module>
    from tindetheus import export_embeddings
  File "/tindetheus/tindetheus/export_embeddings.py", line 88, in <module>
    from tindetheus.facenet_clone.align import detect_face
  File "/tindetheus/tindetheus/facenet_clone/align/detect_face.py", line 34, in <module>
    import cv2
  File "/usr/local/lib/python3.6/dist-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

which was fixed with

```
apt install libgl1-mesa-glx
```

And now I get the authentication issue here:

```
root@ac1f190e018a:/tinder# tindetheus browse
Traceback (most recent call last):
  File "/usr/local/bin/tindetheus", line 33, in <module>
    sys.exit(load_entry_point('tindetheus', 'console_scripts', 'tindetheus')())
  File "/tindetheus/tindetheus/tindetheus.py", line 279, in command_line_run
    retries=defaults['retries'])
  File "/tindetheus/tindetheus/tindetheus.py", line 80, in main
    likes_left=args.likes, x_auth_token=x_auth_token)
  File "/tindetheus/tindetheus/tinder_client.py", line 89, in __init__
    self.session = self.login(facebook_token, x_auth_token)
  File "/tindetheus/tindetheus/tinder_client.py", line 127, in login
    XAuthToken=x_auth_token)
  File "/usr/local/lib/python3.6/dist-packages/pynder/session.py", line 18, in __init__
    self._api.auth(facebook_id, facebook_token)
  File "/usr/local/lib/python3.6/dist-packages/pynder/api.py", line 41, in auth
    raise errors.RequestError(err)
pynder.errors.RequestError: Couldn't authenticate request status code: 401
```

Which I think is further than you were able to get, and thindetheus train worked successfully. (I don't currently have a method to test authentication).

I'm going to push a change to the docker build to include libgl. That docker build is two months old. Then we will see what happens.

I didn't run into your problem, but it's not impossible with the magnitude of dependencies. I suspect it can be fixed with `python3 -m pip install importlib-metadata`

**Comment by cjekel** [comment]
@MajorLOL You are still getting core dumps?

**Comment by MajorLOL** [comment]
![image](https://user-images.githubusercontent.com/56225967/106777267-1ff72800-6645-11eb-8336-d8cbf8a93d77.png)
Still the same problem.

> @MajorLOL You are still getting core dumps?

**Comment by cjekel** [comment]
does `tindetheus --help` give core dump too

**Comment by MajorLOL** [comment]
> does `tindetheus --help` give core dump too

Yes

**Comment by cjekel** [comment]
Just a sanity check while I wait for the new docker build.

Just make sure plane python works.

`python3 -c 'print("hello world")'`

**Comment by MajorLOL** [comment]
> Just a sanity check while I wait for the new docker build.
> 
> Just make sure plane python works.
> 
> `python3 -c 'print("hello world")'`

![image](https://user-images.githubusercontent.com/56225967/106778035-d4914980-6645-11eb-8c72-2277595c7d1d.png)
Gotta to home from work now ill check this post when i am home 30 min. let me know if you need me to do other thing to test.

**Comment by MajorLOL** [comment]
> Just a sanity check while I wait for the new docker build.
> 
> Just make sure plane python works.
> 
> `python3 -c 'print("hello world")'`

Greetings, i saw you did an update. Currently i am receiving the same error.
Can you contact me on Discord maybe? so i can screen share? id: 206496897022558209 Anónymous #7301

**Comment by MajorLOL** [comment]
Even when running fresh install and not putting in the folders give the same result

**Comment by cjekel** [comment]
Sorry I got caught up in my work.

I tested the latest automatic build from docker and it was working fine. I take it you have been building this yourself? 

https://hub.docker.com/r/cjekel/tindetheus

So I just run `docker pull cjekel/tindetheus` instead of `docker build`. I think the image is like 10 Gb of data, so watch your bandwidth.

Are you using any unusual hardware (Arm? apple m1?)

**Comment by MajorLOL** [comment]
Greetings,

Running it on my Synology, i tried everything but all with the same results.
It says 
latest: Pulling from cjekel/tindetheus
Digest: sha256:b6dc4ca572432a3628f1b050e760171b9273a5222a62d0e88a5d92ae257a5ba3
Status: Image is up to date for cjekel/tindetheus:latest

**Comment by cjekel** [comment]
Sorry for the late reply.

I suspect something docker on that machine isn't working correctly on that hardware. Most likely it's something with the old tensorflow.

Is it possible to do the [native-setup](https://github.com/cjekel/tindetheus/blob/master/GETTING_STARTED.md#native-setup ) on your machine? (I know that docker is suppose to avoid these issues, but I can't reproduce your docker problems on my machines :( )

**Comment by MajorLOL** [comment]
Sorry for the late reaction,
Used image:
https://registry.hub.docker.com/_/python/

followed commands in link and received:
ERROR: Could not find a version that satisfies the requirement tensorflow<2.0.0
ERROR: No matching distribution found for tensorflow<2.0.0
using docker 18.09.0-0519 (latest) on synology

used command: pip install tensorflow

Receiving same message before doing install tensorflow or after both on new images.
Will search more info later.

**Comment by cjekel** [comment]
@MajorLOL I think it's too new of a python version, that tensorflow 1.15 was never release for? Tensorflow 1 only goes up to python 3.7 support https://pypi.org/project/tensorflow/1.15.5/ 

So can you check which version of python that is using?

**Comment by MajorLOL** [comment]
@cjekel can you please point me in the right direction?
I tryed many differend once without succes:
https://registry.hub.docker.com/_/python/?tab=tags&page=1&ordering=last_updated
